### ISSUE TITLE
Error: application/vnd.api+json

### ISSUE THREAD

**Issue by dfjosh** [zoltan-nz/tutorial-builder-backend#1]
Have you tried this with Rails 5.0? When I curl a resource (like shown on this example app: https://github.com/cerebris/peeps/tree/master) `curl -i -H "Accept: application/vnd.api+json" "http://localhost:3000/sandbox"` it works fine. But when I go to http://localhost:3000/sandbox in a browser, I get the following error: 

```
{"errors":[{"title":"Not acceptable","detail":"All requests must use the 'application/vnd.api+json' Accept without media type parameters. This request specified 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'.","code":"406","status":"406"}]}
```

I've tried following this site's advice https://www.simplify.ba/articles/2016/06/18/creating-rails5-api-only-application-following-jsonapi-specification/#media-type but without success.

**Comment by zoltan-nz** [comment]
@dfjosh this is intentional, so the Rails 5 API with `jsonapi-resources` gem allows json requests/responses only as default.

You can see in the log, when you request from a browser (which `Accept` header value is `text/html`), the response is a `406`.

``` bash
Processing by SandboxesController#index as HTML
Filter chain halted as :ensure_valid_accept_media_type rendered or redirected
Completed 406 Not Acceptable in 7ms (Views: 0.4ms | ActiveRecord: 0.0ms)
```

However, if you send a request from javascript or from a curl, you got the expected `200` response.

``` bash
Started GET "/sandboxes" for ::1 at 2016-08-02 20:38:05 +1200
Processing by SandboxesController#index as */*
  Parameters: {"sandbox"=>{}}
  Sandbox Load (0.1ms)  SELECT "sandboxes".* FROM "sandboxes" ORDER BY "sandboxes"."id" ASC
Completed 200 OK in 8ms (Views: 0.5ms | ActiveRecord: 0.6ms)
```

Connected documentation: https://github.com/cerebris/jsonapi-resources#action-callbacks

Related code: https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/acts_as_resource_controller.rb#L137-L167

**Comment by dfjosh** [comment]
Thank you for explaining that. I'm used to testing my requests in the browser. Also, thanks for tutorial app!

**Comment by zoltan-nz** [comment]
@dfjosh try out Postman or Insomnia, great tools for testing APIs.

Postman: https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

Insomnia: https://chrome.google.com/webstore/detail/insomnia-rest-client/gmodihnfibbjdecbanmpmbmeffnmloel?hl=en

**Comment by dfjosh** [comment]
Hey thanks for the recommendation. Been using Postman all day!
